### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tommyp6** [ghaiklor/ghaiklor-os-gcc#1]
@ghaiklor I have a question. If I' ve got a file called : `helloworld.c` :
```c
#include <stdio.h>

int main(int argc, char **argv)
{
	printf("Hello World !!!\n");
	return(0);
}
```

I want to be able to add it to a USB and be able to run it.
I saw assembly things but I don't understand. Could you help me to do it ?

Thank you @TommyPujol06

**Comment by ghaiklor** [comment]
Is this related to this project ? What is expected result ? Sorry, but it seems like your question is not related to the project, am I wrong ?

**Comment by tommyp6** [comment]
No, It is not related to the project, just asking.

**Comment by ghaiklor** [comment]
In that case I must close the issue as unrelated to the project.

Regard to your question, read more about compilers - that is the thing you need to be able to run the code from topic.

**Comment by tommyp6** [comment]
Ok, thanks.
