### ISSUE TITLE
VirtualBox Question and Screen Support

### ISSUE THREAD

**Issue by JohnnyErnest** [ghaiklor/ghaiklor-os-gcc#2]
Firstly I just wanted to say thank you Eugene for such a wonderful project! It's helped me gain some understanding into making an OS. I've got the project working on OSX with QEMU. I have for some time wanted to build an OS.

I also wanted to test though under VirtualBox as either an IMG, ISO, or CUE/BIN. Could you please help me with some guidance on what's the best route to take? VirtualBox will not load the os-image BIN by itself, claiming that it can't find out the file format, even though it's obviously raw binary. 

Perhaps with a little guidance I could help with the project with creating scripts for outputting the needed file formats for different virtual machine emulators. 

I also want to look into outputting graphics to the screen, such as a splash screen at a decent resolution that is standard to displays, that could take quite some work, but I feel is worth some effort to extend the project.

**Comment by ghaiklor** [comment]
You are welcome, my project is based on these great resources I learnt from:
http://www.cs.bham.ac.uk/%7Eexr/lectures/opsys/10_11/lectures/os-dev.pdf
http://www.brokenthorn.com/Resources/OSDevIndex.html
So, you can find some helpful info there as well.

I'm not sure about VirtualBox, didn't even have a plan to support it, but maybe converting from raw to vdi image will help: https://www.virtualbox.org/manual/ch08.html#vboxmanage-convertfromraw

> Perhaps with a little guidance I could help with the project with creating scripts for outputting the needed file formats for different virtual machine emulators.

Feel free to fork it and play there. I wanted to keep this project as simple as possible for beginners to dig in, so I am not sure this is a good idea to introduce custom build processes.

Though, regard to videocard driver, if the section will be explained in "How it works", why not. Implement the driver, explain how it works and I'll merge it 👍
