### ISSUE TITLE
Having an issue with reading the disk

### ISSUE THREAD

**Issue by yousufotkani** [ghaiklor/ghaiklor-os-gcc#3]
Hello there.
I am also trying to write a simple os and following this pdf, http://www.cs.bham.ac.uk/~exr/lectures/opsys/10_11/lectures/os-dev.pdf.

I have written pretty the same code as yours. But I am not able to read from the hard disk and always end up in Disk error. Did you face any similar problems? If you could help me solve the issue, it could be pretty helpful.

This is my git: https://github.com/yousufotkani/thuthie_os.git 

Thanks

**Comment by ghaiklor** [comment]
@yousufotkani it was a long time ago and I remember nothing about it anymore 🤷
